"""empty message

Revision ID: 1be529875b9
Revises: 21e0b274d19
Create Date: 2015-05-14 10:56:10.955439

"""

# revision identifiers, used by Alembic.
revision = '1be529875b9'
down_revision = '21e0b274d19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_skills', 'age')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_skills', sa.Column('age', sa.DATE(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
