"""empty message

Revision ID: 208791670bd
Revises: 317c44e3d0a
Create Date: 2015-05-06 09:31:43.802104

"""

# revision identifiers, used by Alembic.
revision = '208791670bd'
down_revision = '317c44e3d0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'skilldescription')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('skilldescription', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    ### end Alembic commands ###
