"""empty message

Revision ID: 21e0b274d19
Revises: 28996ac7bef
Create Date: 2015-05-14 10:54:27.029965

"""

# revision identifiers, used by Alembic.
revision = '21e0b274d19'
down_revision = '28996ac7bef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
