"""empty message

Revision ID: 28996ac7bef
Revises: 51bcd4a0464
Create Date: 2015-05-06 16:34:04.739782

"""

# revision identifiers, used by Alembic.
revision = '28996ac7bef'
down_revision = '51bcd4a0464'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trill_role_skill_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trill_role_group_id', sa.Integer(), nullable=True),
    sa.Column('skill_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_group_id'], ['skill_groups.id'], ),
    sa.ForeignKeyConstraint(['trill_role_group_id'], ['trill_role_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('job_titles', sa.Column('trill_role_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_titles', 'trill_role_groups', ['trill_role_group_id'], ['id'])
    op.drop_constraint('skill_groups_trill_role_group_id_fkey', 'skill_groups', type_='foreignkey')
    op.drop_column('skill_groups', 'trill_role_group_id')
    op.drop_constraint('trill_role_groups_job_title_id_fkey', 'trill_role_groups', type_='foreignkey')
    op.drop_column('trill_role_groups', 'job_title_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trill_role_groups', sa.Column('job_title_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('trill_role_groups_job_title_id_fkey', 'trill_role_groups', 'job_titles', ['job_title_id'], ['id'])
    op.add_column('skill_groups', sa.Column('trill_role_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('skill_groups_trill_role_group_id_fkey', 'skill_groups', 'trill_role_groups', ['trill_role_group_id'], ['id'])
    op.drop_constraint(None, 'job_titles', type_='foreignkey')
    op.drop_column('job_titles', 'trill_role_group_id')
    op.drop_table('trill_role_skill_groups')
    ### end Alembic commands ###
