"""empty message

Revision ID: 2a84bfd9058
Revises: 5729d13ee4c
Create Date: 2015-05-06 12:14:00.157325

"""

# revision identifiers, used by Alembic.
revision = '2a84bfd9058'
down_revision = '5729d13ee4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'skilldescription')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('skilldescription', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
    ### end Alembic commands ###
