"""empty message

Revision ID: 2d26b42270b
Revises: 1be529875b9
Create Date: 2015-05-14 10:57:05.111656

"""

# revision identifiers, used by Alembic.
revision = '2d26b42270b'
down_revision = '1be529875b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_skills', sa.Column('age', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_skills', 'age')
    ### end Alembic commands ###
