"""empty message

Revision ID: 30492e4d80e
Revises: 2a84bfd9058
Create Date: 2015-05-06 12:14:41.100464

"""

# revision identifiers, used by Alembic.
revision = '30492e4d80e'
down_revision = '2a84bfd9058'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('skilldescription', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'skilldescription')
    ### end Alembic commands ###
