"""empty message

Revision ID: 317c44e3d0a
Revises: 43b708fdda8
Create Date: 2015-05-05 16:49:10.500479

"""

# revision identifiers, used by Alembic.
revision = '317c44e3d0a'
down_revision = '43b708fdda8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trill_role_groups_groupname_key', 'trill_role_groups', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('trill_role_groups_groupname_key', 'trill_role_groups', ['groupname'])
    ### end Alembic commands ###
