"""empty message

Revision ID: 336d99d96ec
Revises: None
Create Date: 2015-04-30 10:58:30.661709

"""

# revision identifiers, used by Alembic.
revision = '336d99d96ec'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
