"""empty message

Revision ID: 466489f90e6
Revises: 595c61c3db5
Create Date: 2015-06-01 12:04:24.158498

"""

# revision identifiers, used by Alembic.
revision = '466489f90e6'
down_revision = '595c61c3db5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_skill_id_index', 'user_skills', ['skill_id', 'user_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    drop_index("user_skill_id_index")
    ### end Alembic commands ###
