"""empty message

Revision ID: 49538b2e89b
Revises: 167f91ee17f
Create Date: 2015-04-17 11:05:42.433300

"""

# revision identifiers, used by Alembic.
revision = '49538b2e89b'
down_revision = '167f91ee17f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname2', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'surname2')
    ### end Alembic commands ###
