"""empty message

Revision ID: 51bcd4a0464
Revises: 30492e4d80e
Create Date: 2015-05-06 15:12:51.229550

"""

# revision identifiers, used by Alembic.
revision = '51bcd4a0464'
down_revision = '30492e4d80e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_groups', sa.Column('skilltype', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_groups', 'skilltype')
    ### end Alembic commands ###
