"""empty message

Revision ID: 5729d13ee4c
Revises: 208791670bd
Create Date: 2015-05-06 11:45:02.191591

"""

# revision identifiers, used by Alembic.
revision = '5729d13ee4c'
down_revision = '208791670bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('skilldescription', sa.String(length=400), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'skilldescription')
    ### end Alembic commands ###
