"""empty message

Revision ID: 595c61c3db5
Revises: 2d26b42270b
Create Date: 2015-05-29 14:22:52.568763

"""

# revision identifiers, used by Alembic.
revision = '595c61c3db5'
down_revision = '2d26b42270b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_role_stage',
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('surname', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('trill_role_group', sa.String(length=80), nullable=True),
    sa.Column('managerfirstname', sa.String(length=80), nullable=True),
    sa.Column('managersurname', sa.String(length=80), nullable=True),
    sa.Column('job_title', sa.String(length=80), nullable=True),
    sa.Column('encrypted_passwd', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('skill_mapping_stage',
    sa.Column('skilltype', sa.String(length=10), nullable=True),
    sa.Column('skillgroup', sa.String(length=80), nullable=True),
    sa.Column('skilltitlename', sa.String(length=240), nullable=True),
    sa.Column('skilldescription', sa.String(), nullable=True),
    sa.Column('skillcode', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_role_stage',
    sa.Column('trill_role_group', sa.String(length=80), nullable=True),
    sa.Column('skillgroup', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('skill_titles', 'skilltitlename',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=240),
               existing_nullable=True)
#   Alembic cannot handle column changes to Integer type so we have to do it using
#   DDL on the database itself.
    op.execute('ALTER TABLE user_skills ALTER COLUMN confidence TYPE integer USING (confidence::integer)')
#    op.alter_column('user_skills', 'confidence',
#               existing_type=sa.VARCHAR(length=20),
#               type_=sa.Integer(),
#               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_skills', 'confidence',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('skill_titles', 'skilltitlename',
               existing_type=sa.String(length=240),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.drop_table('skill_role_stage')
    op.drop_table('skill_mapping_stage')
    op.drop_table('people_role_stage')
    ### end Alembic commands ###
