"""empty message

Revision ID: 3596c04237b
Revises: 87315de71f
Create Date: 2015-04-16 23:04:09.679020

"""

# revision identifiers, used by Alembic.
revision = '3596c04237b'
down_revision = '87315de71f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'surname2')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname2', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    ### end Alembic commands ###
